os:
  - linux
language:
  - python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -r test_requirements.txt
script:
  - py.test model.py --pep8 model.py --cov model.py -v
after_success:
  - coveralls
