language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install pytest-pep8
  - pip3 install pytest-cov
  - pip3 install python-coveralls
# command to run tests
script: coverage run --source HomeTask11/model.py HomeTask11/test_model.py
after_success: 
- coveralls
